### ISSUE TITLE
npm version is behind

### ISSUE THREAD

**Issue by jimf** [paldepind/union-type#19]
Current version: 0.1.6
npm version: 0.1.4

**Comment by davidchambers** [comment]
@paldepind, would you like a pull request to integrate [xyz][1]?


[1]: https://github.com/davidchambers/xyz

**Comment by paldepind** [comment]
@davidchambers I would certainly like and appreciate such a pull request!

**Comment by jimf** [comment]
```sh
% npm view union-type version
0.1.6
```

Thanks!
