### ISSUE TITLE
Support lists of types natively or via an exposed predicate.

### ISSUE THREAD

**Issue by JAForbes** [paldepind/union-type#48]
Is there a way to make a type checked collection?

``` js
const Header = Type({
    Header: { 
        signature: String
        , byteOffset: Number
        , signatureName: String 
    }
})

const Model = Type({
        Model: { headers: R.all(Header.is) }
})
```

`Header.is` doesn't exist currently, but I'm imaging if a union had a predicate
 you could create things like `R.both( R.isArray, R.all(Header.is) )` to specify that field should be a `Header[]`.

If there is a simpler approach as well, that would be great! 👍 

I think it'd be nice to be able to specify a list of a given type as a built in behaviour as well.

E.g.

``` js
const Model = Type({
        // wrap a record in an array to signify Header[]
        Model: { headers: [Header] }
        // or for a non record type
        Model: [ [Header] ]
        // or dynamically add a property to signify Header[]
        Model: { headers: Header.List } 
        Model: [ Header.List ]
})

```

If we had access to the internal prototypes, we could use `R.is`, or `a.isPrototypeOf(A)`, but I think the currying gets in the way of that.

**Comment by paldepind** [comment]
Hello. I've just done a release with #41. Does the feature in that PR do what you want?

**Comment by JAForbes** [comment]
Wow 😲 that's great.

I still think it would be nice if every union exposed a predicate.  But I'm happy with this new feature. 👌 

-----Original Message-----
