### ISSUE TITLE
Remove requirement of nesting perhaps?

### ISSUE THREAD

**Issue by timoxley** [paldepind/union-type#9]
Would be good if one could define types without requiring nesting inside an object:

```js

// e.g. pass array without nesty object
const Point = Type([isNumber, isNumber])

var p = Point('bad', 4) // no Point.Point :)

// or pass a function directly
const SomeNumber = Type(isNumber)
const AlternativePoint = Type([SomeNumber, SomeNumber])
var p = AlternativePoint('bad', 4) // still no nesting
```

**Comment by paldepind** [comment]
I think you're confusing types with values. If you where to define the boolean type with union-type it would look like this:

```javascript
var Boolean = Type({True: [], False: []});
```

Here `Boolean` is the type and `True` and `False` are values. So what you're asking is really to define a value without it belonging to a type.

What benefits do you think this would offer? Maybe a shortcut for defining a type with only a single possible value would be better?

**Comment by timoxley** [comment]
hm, I don't know what I'm asking anymore, nvm. :+1:

**Comment by paldepind** [comment]
No problem!
